### PR TITLE
[#40] Applies elixir formatter

### LINKED ISSUE #40: Apply elixir formatter

### PR DESCRIPTION
**Pull request by pragmaticivan**
fixes #40

### CODE REVIEW

**Comment by mustafaturan** [comment]
Could you please set line length to 80 chars and re-submit?

**Comment by mustafaturan** [comment]
@pragmaticivan ^

**Comment by pragmaticivan** [comment]
Done @mustafaturan

**Comment by mustafaturan** [comment]
Before merge could you please squash your commits into 1?

**Comment by pragmaticivan** [comment]
I can, btw, Github has that functionality when you merge a PR you can choose to squash into the one and it uses the title of the PR.

**Pull request merged**
